#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Meng-Huan Yu"
email = "2252236+cebrusfs@users.noreply.github.com"

[ui]
default-command = "log"
pager = ["sh", "-c", "~/.dotfiles/modules/diff-so-fancy/diff-so-fancy | less --tabs=4 -RFX"]
diff-formatter = ":git"
diff-editor = ":builtin"
merge-editor = "vscode"

[colors]
# Highlight hunks with background
"diff removed token" = { bg = "#221111", underline = false }
"diff added token" = { bg = "#002200", underline = false }
