#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Meng-Huan Yu"
email = "2252236+cebrusfs@users.noreply.github.com"

[ui]
default-command = "log"

# Use diff format and diff-so-facny as pager
diff-formatter = ":git"
pager = "delta"

# Editors
diff-editor = ":builtin"
merge-editor = "vimdiff"
