#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Meng-Huan Yu"
email = "2252236+cebrusfs@users.noreply.github.com"

[ui]
default-command = "log"

# Use diff format and diff-so-facny as pager
diff-formatter = ":git"

# On 0.36.0+, the $PAGER is ignored and have to explicitly setup by default.
pager = "delta"

# Editors
diff-editor = ":builtin"
merge-editor = "vimdiff"
show-cryptographic-signatures = true

[git]
# Prevent upload
private-commits = 'blacklist()'

# Sign on push, work together with behavior = "drop"
# sign-on-push = true

# Automatically track all branches/bookmarks on `origin` remote
[remotes.origin]
auto-track-bookmarks = "glob:*"

[aliases]
blame = ["file", "annotate"]
bl = ["blame"]

[revset-aliases]
# Private and WIP commits that should never be pushed anywhere. Often part of
# work-in-progress merge stacks.
'wip()' = 'description(glob:"wip:*")'
'private()' = 'description(glob:"private:*") | description(glob:"DO.?NOT.?SUBMIT:*")'
'blacklist()' = 'wip() | private()'

[signing]
key = "~/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "~/.config/git/allowed_signers"

# Enable signing
# backend = "ssh"
# behavior = "own"
