#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Meng-Huan Yu"
email = "2252236+cebrusfs@users.noreply.github.com"

[ui]
default-command = "log"

# Use diff format and diff-so-facny as pager
diff-formatter = ":git"
pager = "delta"

# Editors
diff-editor = ":builtin"
merge-editor = "vimdiff"

[git]
# When jj imports a new remote-tracking bookmark from Git, it can also create a local bookmark with the same name.
auto-local-bookmark = true

# jj git push does not push newly-created bookmarks by default. If you do not want to specify --allow-new
push-new-bookmarks = true

# Prevent upload
private-commits = 'blacklist()'

[aliases]
blame = ["file", "annotate"]
bl = ["blame"]

[revset-aliases]
# Private and WIP commits that should never be pushed anywhere. Often part of
# work-in-progress merge stacks.
'wip()' = 'description(glob:"wip:*")'
'private()' = 'description(glob:"private:*") | description(glob:"DO.?NOT.?SUBMIT:*")'
'blacklist()' = 'wip() | private()'

[signing]
# Change to other things will enable auto signing
backend = "none"
#backend = "ssh"

key = "~/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "~/.config/git/allowed_signers"
